/// Flutter icons WeezlyIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeezlyIcon
///      fonts:
///       - asset: fonts/WeezlyIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class WeezlyIcon {
  WeezlyIcon._();

  static const _kFontFam = 'WeezlyIcon';
  static const String? _kFontPkg = null;

  static const IconData arrow_right = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_circle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData identity = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kg = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profil = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clothe = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData little_package = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sofa = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_package = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boat = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camion = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cb = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mastercard = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paylib = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visa = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_train = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_car = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_plane = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_bus = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_boat = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_camion = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_square = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkout = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_empty = IconData(0xf1d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_official = IconData(0xf230, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
